# Title of your blog; shows in the header
name: "|ω・) Interest-Driven Blogging"

# Description of your content (will only be used on Google Search)
description: "ogaclejapan's blog about the development"

# Your name. Will show in your footer + sidebar
author: "ogaclejapan"
lang: ja
timezone: Asia/Tokyo

url: "http://blog.ogaclejapan.com"
baseurl: ""

# A short presentation of yourself. Will show in the sidebar, under your name. Best usage would be between 30 to 50 words.
author-bio: "Android Software Engineer at AbemaTV"

# Social Accounts (mine, as placeholders)
twitter: ogaclejapan
github: ogaclejapan
dribbble:
instagram:
googleplus: 115224314007024961072

# Google Analytics (you may want to changes these with yours or even delete :)
ga_tracking_id: UA-37241684-4

# Handling Reading
exclude: ["README.md", ".gitignore", "Gemfile", "Gemfile.lock", "vendor", "art", ".travis.yml"]

# Plugins
gems: [jekyll-redirect-from, jekyll-paginate]

# Conversion
markdown: kramdown
highlighter: rouge

# Outputting
permalink: pretty
paginate: 10
paginate_path: "/page/:num"

# Markdown Processors
kramdown:
  input: GFM

# SCSS
sass:
  sass_dir: _scss
  style: :compressed

